#!/usr/bin/env zsh
export LANG=en_GB.UTF-8
export LC_ALL=en_GB.UTF-8

export EDITOR='vim'


export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:$PATH"

if [[ -d /opt/homebrew/bin ]]; then
  export PATH="/opt/homebrew/bin:$PATH"
fi

if [[ -d /opt/homebrew/opt/openssl@3/bin ]]; then
  export PATH="/opt/homebrew/opt/openssl@3/bin:$PATH"
fi

export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
